[2025-03-03T06:48:59.944+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test.py
[2025-03-03T06:48:59.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:48:59.951+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:48:59.951+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:49:00.328+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:49:00.315+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:49:00.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:49:00.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.430 seconds
[2025-03-03T06:49:31.482+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/test.py
[2025-03-03T06:49:31.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:49:31.539+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:49:31.534+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:49:32.923+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:49:32.884+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:49:32.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:49:33.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.724 seconds
[2025-03-03T06:50:49.231+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/test.py
[2025-03-03T06:50:49.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:50:49.253+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:50:49.251+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:50:49.919+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:50:49.906+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:50:49.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:50:49.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.772 seconds
[2025-03-03T06:51:21.039+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/test.py
[2025-03-03T06:51:21.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:51:21.044+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:51:21.044+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:51:21.386+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:51:21.375+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:51:21.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:51:21.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.419 seconds
[2025-03-03T06:51:52.050+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/test.py
[2025-03-03T06:51:52.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:51:52.063+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:51:52.060+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:51:52.396+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:51:52.385+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:51:52.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:51:52.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.386 seconds
[2025-03-03T06:52:23.403+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/test.py
[2025-03-03T06:52:23.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:52:23.409+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:52:23.408+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:52:23.799+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:52:23.789+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:52:23.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:52:23.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.437 seconds
[2025-03-03T06:52:54.806+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/test.py
[2025-03-03T06:52:54.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:52:54.835+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:52:54.831+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:52:55.115+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:52:55.108+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:52:55.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:52:55.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.345 seconds
[2025-03-03T06:53:26.172+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/test.py
[2025-03-03T06:53:26.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:53:26.186+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:53:26.185+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:53:26.677+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:53:26.666+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:53:26.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:53:26.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.569 seconds
[2025-03-03T06:53:56.818+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/test.py
[2025-03-03T06:53:56.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:53:56.822+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:53:56.822+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:53:57.098+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:53:57.089+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:53:57.100+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:53:57.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.304 seconds
[2025-03-03T06:54:27.565+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/test.py
[2025-03-03T06:54:27.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:54:27.578+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:54:27.577+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:54:27.943+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:54:27.933+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:54:27.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:54:27.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.431 seconds
[2025-03-03T06:54:58.554+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/test.py
[2025-03-03T06:54:58.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:54:58.559+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:54:58.558+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:54:58.777+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:54:58.769+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:54:58.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:54:58.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.246 seconds
[2025-03-03T06:55:28.919+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/test.py
[2025-03-03T06:55:28.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:55:28.923+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:55:28.923+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:55:29.088+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:55:29.081+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:55:29.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:55:29.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.198 seconds
[2025-03-03T06:55:59.334+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/test.py
[2025-03-03T06:55:59.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:55:59.338+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:55:59.337+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:55:59.625+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:55:59.616+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T06:55:59.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:55:59.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.338 seconds
[2025-03-03T06:56:29.927+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/test.py
[2025-03-03T06:56:29.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:56:29.958+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:29.956+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:56:30.382+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:30.382+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T06:56:30.393+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:30.393+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T06:56:30.405+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:30.404+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T06:56:30.408+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:30.408+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T06:56:32.161+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:32.161+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T06:56:32.162+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:32.162+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T06:56:32.163+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:32.163+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T06:56:32.164+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:56:32.164+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T06:57:55.013+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/test.py
[2025-03-03T06:57:55.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:57:55.030+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:55.029+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:57:55.503+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:55.502+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T06:57:55.504+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:55.504+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T06:57:55.507+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:55.506+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T06:57:55.508+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:55.507+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T06:57:58.225+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.225+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T06:57:58.226+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.226+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T06:57:58.227+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.227+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T06:57:58.228+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.228+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T06:57:58.664+0000] {processor.py:925} INFO - DAG(s) 'ml_dag', 'lab1_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:57:58.819+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.818+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:ml_dag
[2025-03-03T06:57:58.836+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.836+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:ml_dag
[2025-03-03T06:57:58.845+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.844+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:ml_dag
[2025-03-03T06:57:58.855+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.854+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:ml_dag
[2025-03-03T06:57:58.863+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.863+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:ml_dag
[2025-03-03T06:57:58.872+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.872+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:ml_dag
[2025-03-03T06:57:58.883+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.882+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:ml_dag
[2025-03-03T06:57:58.915+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:58.914+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T06:57:59.594+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:59.593+0000] {dag.py:3252} INFO - Creating ORM DAG for ml_dag
[2025-03-03T06:57:59.608+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:59.608+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:50:00+00:00, run_after=2025-03-03 06:55:00+00:00
[2025-03-03T06:57:59.613+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:57:59.613+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:50:00+00:00, run_after=2025-03-03 06:55:00+00:00
[2025-03-03T06:57:59.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 4.669 seconds
[2025-03-03T06:58:30.189+0000] {processor.py:186} INFO - Started process (PID=287) to work on /opt/airflow/dags/test.py
[2025-03-03T06:58:30.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T06:58:30.194+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:30.194+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T06:58:30.436+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:30.435+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T06:58:33.550+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:33.549+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T06:58:33.551+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:33.551+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T06:58:33.552+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:33.552+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T06:58:34.185+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:34.185+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T06:58:34.186+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:34.186+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T06:58:34.187+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:34.187+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T06:58:34.187+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:34.187+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T06:58:34.666+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T06:58:34.701+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:34.700+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T06:58:34.796+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:34.796+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:50:00+00:00, run_after=2025-03-03 06:55:00+00:00
[2025-03-03T06:58:34.802+0000] {logging_mixin.py:190} INFO - [2025-03-03T06:58:34.802+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:50:00+00:00, run_after=2025-03-03 06:55:00+00:00
[2025-03-03T06:58:34.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 4.643 seconds
[2025-03-03T07:00:44.461+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/test.py
[2025-03-03T07:00:44.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:00:44.474+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:44.472+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:00:45.342+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:45.342+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:00:45.343+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:45.343+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:00:45.345+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:45.344+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:00:45.345+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:45.345+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:00:46.501+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:46.501+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:00:46.504+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:46.503+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:00:46.505+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:46.504+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:00:46.505+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:46.505+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:00:47.032+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:00:47.145+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:47.144+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:00:47.373+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:47.372+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:00:47.378+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:00:47.378+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:00:47.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 3.008 seconds
[2025-03-03T07:01:17.594+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/test.py
[2025-03-03T07:01:17.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:01:17.601+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:17.600+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:01:18.338+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:18.336+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:01:18.340+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:18.339+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:01:18.343+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:18.343+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:01:18.347+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:18.346+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:01:19.208+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:19.207+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:01:19.209+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:19.209+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:01:19.211+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:19.210+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:01:19.211+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:19.211+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:01:19.640+0000] {processor.py:925} INFO - DAG(s) 'ml_dag', 'lab1_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:01:19.700+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:19.699+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:01:19.883+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:19.882+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:01:19.891+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:19.890+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:01:19.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 2.394 seconds
[2025-03-03T07:01:50.374+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/test.py
[2025-03-03T07:01:50.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:01:50.378+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:50.378+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:01:50.595+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:50.594+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:01:50.599+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:50.599+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:01:50.602+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:50.601+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:01:50.603+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:50.603+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:01:51.311+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:51.311+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:01:51.312+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:51.312+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:01:51.313+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:51.313+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:01:51.314+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:51.314+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:01:51.762+0000] {processor.py:925} INFO - DAG(s) 'ml_dag', 'lab1_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:01:51.797+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:51.797+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:01:52.045+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:52.045+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:01:52.063+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:01:52.063+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:01:52.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 2.101 seconds
[2025-03-03T07:02:22.956+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/test.py
[2025-03-03T07:02:22.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:02:22.960+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:22.959+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:02:23.121+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.120+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:02:23.125+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.124+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:02:23.127+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.127+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:02:23.128+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.128+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:02:23.646+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.645+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:02:23.647+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.647+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:02:23.648+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.648+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:02:23.649+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:23.649+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:02:24.002+0000] {processor.py:925} INFO - DAG(s) 'ml_dag', 'lab1_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:02:24.120+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:24.120+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:02:24.317+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:24.317+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:02:24.328+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:24.327+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:02:24.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.433 seconds
[2025-03-03T07:02:54.452+0000] {processor.py:186} INFO - Started process (PID=335) to work on /opt/airflow/dags/test.py
[2025-03-03T07:02:54.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:02:54.457+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:54.457+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:02:54.635+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:54.635+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:02:54.637+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:54.636+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:02:54.638+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:54.638+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:02:54.639+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:54.639+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:02:55.159+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:55.158+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:02:55.160+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:55.159+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:02:55.161+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:55.160+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:02:55.161+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:55.161+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:02:55.521+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:02:55.542+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:55.541+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:02:55.623+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:55.623+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:02:55.628+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:02:55.628+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:02:55.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.205 seconds
[2025-03-03T07:03:25.839+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/test.py
[2025-03-03T07:03:25.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:03:25.852+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:25.852+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:03:26.043+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.043+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:03:26.045+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.045+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:03:26.046+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.046+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:03:26.047+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.047+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:03:26.751+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.750+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:03:26.752+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.751+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:03:26.753+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.752+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:03:26.753+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:26.753+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:03:27.208+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:03:27.267+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:27.266+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:03:27.461+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:27.461+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:03:27.467+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:03:27.467+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 06:55:00+00:00, run_after=2025-03-03 07:00:00+00:00
[2025-03-03T07:03:27.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.704 seconds
[2025-03-03T07:07:06.433+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/test.py
[2025-03-03T07:07:06.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:07:06.444+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:07:06.443+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:07:06.833+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:07:06.824+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T07:07:06.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:07:06.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.437 seconds
[2025-03-03T07:07:37.375+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/dags/test.py
[2025-03-03T07:07:37.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:07:37.394+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:07:37.390+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:07:38.515+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:07:38.414+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T07:07:38.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:07:38.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.257 seconds
[2025-03-03T07:08:09.625+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/test.py
[2025-03-03T07:08:09.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:08:09.628+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:08:09.628+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:08:09.831+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:08:09.823+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T07:08:09.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:08:09.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-03-03T07:08:40.078+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/test.py
[2025-03-03T07:08:40.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:08:40.082+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:08:40.082+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:08:40.273+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:08:40.265+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T07:08:40.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:08:40.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.213 seconds
[2025-03-03T07:09:10.681+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/test.py
[2025-03-03T07:09:10.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:09:10.684+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:10.684+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:09:10.840+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:10.833+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 164, in <module>
    conn = return_snowflake_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 299, in get_conn
    conn_config = self._get_conn_params
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 192, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_conn` isn't defined
[2025-03-03T07:09:10.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:09:10.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.176 seconds
[2025-03-03T07:09:40.952+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/test.py
[2025-03-03T07:09:40.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:09:40.959+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:40.958+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:09:41.621+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:41.619+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:09:41.650+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:41.648+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:09:41.672+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:41.671+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:09:41.676+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:41.675+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:09:43.105+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.105+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:09:43.106+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.106+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:09:43.107+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.107+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:09:43.108+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.108+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:09:43.452+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:09:43.701+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.700+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:ml_dag
[2025-03-03T07:09:43.709+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.709+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:ml_dag
[2025-03-03T07:09:43.717+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.717+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:ml_dag
[2025-03-03T07:09:43.725+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.725+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:ml_dag
[2025-03-03T07:09:43.732+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.732+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:ml_dag
[2025-03-03T07:09:43.738+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.738+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:ml_dag
[2025-03-03T07:09:43.746+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.746+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:ml_dag
[2025-03-03T07:09:43.747+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.746+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:09:43.764+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.764+0000] {dag.py:3252} INFO - Creating ORM DAG for ml_dag
[2025-03-03T07:09:43.777+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.777+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:05:00+00:00, run_after=2025-03-03 07:10:00+00:00
[2025-03-03T07:09:43.782+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:09:43.782+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:00:00+00:00, run_after=2025-03-03 07:05:00+00:00
[2025-03-03T07:09:43.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 2.897 seconds
[2025-03-03T07:10:14.068+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/test.py
[2025-03-03T07:10:14.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:10:14.072+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.072+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:10:14.230+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.229+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:10:14.231+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.231+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:10:14.232+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.232+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:10:14.233+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.233+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:10:14.679+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.679+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:10:14.680+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.680+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:10:14.681+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.681+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:10:14.682+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:14.681+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:10:15.095+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:10:15.125+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:15.124+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:10:15.153+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:15.153+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:10:15.159+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:15.159+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:05:00+00:00, run_after=2025-03-03 07:10:00+00:00
[2025-03-03T07:10:15.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.115 seconds
[2025-03-03T07:10:45.480+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/test.py
[2025-03-03T07:10:45.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:10:45.485+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:45.485+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:10:45.664+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:45.664+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:10:45.665+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:45.665+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:10:45.667+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:45.667+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:10:45.668+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:45.668+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:10:46.327+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:46.327+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:10:46.328+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:46.328+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:10:46.330+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:46.329+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:10:46.331+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:46.330+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:10:46.816+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:10:46.838+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:46.837+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:10:46.868+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:46.868+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:10:46.875+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:10:46.875+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:05:00+00:00, run_after=2025-03-03 07:10:00+00:00
[2025-03-03T07:10:46.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.423 seconds
[2025-03-03T07:11:17.132+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/test.py
[2025-03-03T07:11:17.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:11:17.137+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.137+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:11:17.317+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.316+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:11:17.321+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.321+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:11:17.325+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.325+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:11:17.327+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.327+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:11:17.869+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.869+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:11:17.870+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.870+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:11:17.871+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.871+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:11:17.872+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:17.872+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:11:18.348+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:11:18.517+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:18.516+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:11:18.547+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:18.547+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:11:18.554+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:18.553+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:11:18.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.454 seconds
[2025-03-03T07:11:48.693+0000] {processor.py:186} INFO - Started process (PID=463) to work on /opt/airflow/dags/test.py
[2025-03-03T07:11:48.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:11:48.697+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:48.697+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:11:48.856+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:48.856+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:11:48.857+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:48.857+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:11:48.859+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:48.858+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:11:48.859+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:48.859+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:11:49.347+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:49.347+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:11:49.348+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:49.348+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:11:49.349+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:49.349+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:11:49.350+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:49.350+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:11:49.687+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:11:49.710+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:49.710+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:11:49.741+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:49.740+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:11:49.748+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:11:49.748+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:11:49.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.082 seconds
[2025-03-03T07:12:19.970+0000] {processor.py:186} INFO - Started process (PID=479) to work on /opt/airflow/dags/test.py
[2025-03-03T07:12:19.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:12:19.977+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:19.976+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:12:20.415+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:20.414+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:12:20.418+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:20.417+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:12:20.420+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:20.420+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:12:20.422+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:20.422+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:12:21.048+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:21.048+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:12:21.052+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:21.052+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:12:21.053+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:21.053+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:12:21.054+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:21.054+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:12:21.406+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:12:21.433+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:21.433+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:12:21.542+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:21.542+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:12:21.564+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:21.564+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:12:21.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.671 seconds
[2025-03-03T07:12:52.024+0000] {processor.py:186} INFO - Started process (PID=496) to work on /opt/airflow/dags/test.py
[2025-03-03T07:12:52.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:12:52.054+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:52.052+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:12:52.713+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:52.711+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:12:52.724+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:52.724+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:12:52.731+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:52.731+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:12:52.734+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:52.733+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:12:53.741+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:53.741+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:12:53.742+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:53.742+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:12:53.743+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:53.743+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:12:53.744+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:53.744+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:12:54.145+0000] {processor.py:925} INFO - DAG(s) 'ml_dag', 'lab1_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:12:54.614+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:54.613+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:12:54.723+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:54.722+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:12:54.732+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:12:54.732+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:12:54.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 2.836 seconds
[2025-03-03T07:13:25.774+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/test.py
[2025-03-03T07:13:25.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:13:25.791+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:25.789+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:13:26.243+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.242+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:13:26.244+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.244+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:13:26.246+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.246+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:13:26.247+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.247+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:13:26.863+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.863+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:13:26.864+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.864+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:13:26.865+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.865+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:13:26.866+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:26.866+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:13:27.278+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:13:27.332+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:27.331+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:13:27.422+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:27.422+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:13:27.433+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:27.432+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:13:27.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.712 seconds
[2025-03-03T07:13:57.983+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/test.py
[2025-03-03T07:13:57.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:13:57.987+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:57.986+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:13:58.172+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.171+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:13:58.173+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.173+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:13:58.174+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.174+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:13:58.175+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.175+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:13:58.687+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.687+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:13:58.689+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.689+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:13:58.690+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.690+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:13:58.692+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:58.691+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:13:59.148+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:13:59.170+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:59.170+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:13:59.197+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:59.197+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:13:59.204+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:13:59.204+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:13:59.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.251 seconds
[2025-03-03T07:14:29.774+0000] {processor.py:186} INFO - Started process (PID=544) to work on /opt/airflow/dags/test.py
[2025-03-03T07:14:29.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:14:29.778+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:29.778+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:14:29.932+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:29.932+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:14:29.934+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:29.934+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:14:29.935+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:29.935+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:14:29.936+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:29.935+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:14:30.594+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:30.594+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:14:30.595+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:30.595+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:14:30.596+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:30.596+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:14:30.597+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:30.597+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:14:31.080+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:14:31.283+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:31.283+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:14:31.309+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:31.309+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:14:31.315+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:14:31.315+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:10:00+00:00, run_after=2025-03-03 07:15:00+00:00
[2025-03-03T07:14:31.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.567 seconds
[2025-03-03T07:15:01.777+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/test.py
[2025-03-03T07:15:01.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:15:01.783+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:01.782+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:15:02.222+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:02.221+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:15:02.232+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:02.230+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:15:02.236+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:02.235+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:15:02.237+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:02.237+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:15:03.264+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:03.264+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:15:03.266+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:03.265+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:15:03.267+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:03.267+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:15:03.267+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:03.267+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:15:03.914+0000] {processor.py:925} INFO - DAG(s) 'ml_dag', 'lab1_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:15:04.222+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:04.221+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:15:04.523+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:04.523+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:15:04.552+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:04.552+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:15:04.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 3.025 seconds
[2025-03-03T07:15:35.500+0000] {processor.py:186} INFO - Started process (PID=598) to work on /opt/airflow/dags/test.py
[2025-03-03T07:15:35.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:15:35.506+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:35.505+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:15:35.711+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:35.710+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:15:35.713+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:35.712+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:15:35.714+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:35.714+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:15:35.715+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:35.715+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:15:36.281+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:36.281+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:15:36.282+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:36.282+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:15:36.283+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:36.283+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:15:36.284+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:36.284+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:15:36.732+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:15:36.753+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:36.752+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:15:36.780+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:36.780+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:15:36.789+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:15:36.788+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:15:36.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.316 seconds
[2025-03-03T07:16:06.910+0000] {processor.py:186} INFO - Started process (PID=614) to work on /opt/airflow/dags/test.py
[2025-03-03T07:16:06.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:16:06.914+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:06.913+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:16:07.071+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.070+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:16:07.072+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.072+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:16:07.074+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.073+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:16:07.074+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.074+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:16:07.709+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.709+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:16:07.711+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.710+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:16:07.712+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.711+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:16:07.713+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:07.712+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:16:08.054+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:16:08.190+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:08.189+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:16:08.220+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:08.219+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:16:08.227+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:08.227+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:16:08.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.350 seconds
[2025-03-03T07:16:38.398+0000] {processor.py:186} INFO - Started process (PID=630) to work on /opt/airflow/dags/test.py
[2025-03-03T07:16:38.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:16:38.402+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:38.402+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:16:38.580+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:38.580+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:16:38.581+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:38.581+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:16:38.583+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:38.582+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:16:38.583+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:38.583+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:16:39.048+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:39.048+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:16:39.049+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:39.049+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:16:39.050+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:39.049+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:16:39.050+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:39.050+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:16:39.444+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:16:39.467+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:39.466+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:16:39.774+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:39.774+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:16:39.781+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:16:39.781+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:16:39.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.410 seconds
[2025-03-03T07:17:10.122+0000] {processor.py:186} INFO - Started process (PID=646) to work on /opt/airflow/dags/test.py
[2025-03-03T07:17:10.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:17:10.126+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.125+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:17:10.293+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.292+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:17:10.294+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.294+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:17:10.295+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.295+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:17:10.296+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.296+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:17:10.747+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.747+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:17:10.748+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.748+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:17:10.749+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.749+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:17:10.750+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:10.749+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:17:11.098+0000] {processor.py:925} INFO - DAG(s) 'ml_dag', 'lab1_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:17:11.123+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:11.122+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:17:11.224+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:11.223+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:17:11.232+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:11.232+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:17:11.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.141 seconds
[2025-03-03T07:17:41.637+0000] {processor.py:186} INFO - Started process (PID=662) to work on /opt/airflow/dags/test.py
[2025-03-03T07:17:41.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:17:41.643+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:41.643+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:17:41.843+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:41.843+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:17:41.845+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:41.845+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:17:41.846+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:41.846+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:17:41.847+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:41.847+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:17:42.493+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:42.493+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:17:42.494+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:42.494+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:17:42.495+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:42.495+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:17:42.496+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:42.495+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:17:42.951+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:17:43.100+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:43.099+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:17:43.198+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:43.197+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:17:44.725+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:17:44.725+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:17:44.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 3.123 seconds
[2025-03-03T07:18:14.997+0000] {processor.py:186} INFO - Started process (PID=678) to work on /opt/airflow/dags/test.py
[2025-03-03T07:18:14.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:18:15.002+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.001+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:18:15.227+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.227+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:18:15.228+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.228+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:18:15.229+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.229+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:18:15.230+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.230+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:18:15.936+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.935+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:18:15.937+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.937+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:18:15.938+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.938+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:18:15.939+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:15.939+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:18:16.351+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:18:16.380+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:16.380+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:18:16.453+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:16.452+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:18:16.460+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:16.460+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:18:16.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.491 seconds
[2025-03-03T07:18:46.786+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/test.py
[2025-03-03T07:18:46.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:18:46.790+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:46.790+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:18:46.947+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:46.947+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:18:46.949+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:46.948+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:18:46.950+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:46.950+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:18:46.951+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:46.951+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:18:47.463+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:47.463+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:18:47.464+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:47.464+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:18:47.465+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:47.465+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:18:47.465+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:47.465+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:18:47.888+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:18:47.907+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:47.906+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:18:47.972+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:47.972+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:18:47.979+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:18:47.979+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:18:48.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.224 seconds
[2025-03-03T07:19:18.490+0000] {processor.py:186} INFO - Started process (PID=710) to work on /opt/airflow/dags/test.py
[2025-03-03T07:19:18.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-03-03T07:19:18.495+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:18.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-03-03T07:19:18.690+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:18.689+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:19:18.691+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:18.691+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:19:18.693+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:18.692+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:19:18.693+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:18.693+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:19:19.694+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:19.694+0000] {base.py:84} INFO - Retrieving connection 'snow_conn'
[2025-03-03T07:19:19.695+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:19.695+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-03T07:19:19.696+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:19.696+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-03T07:19:19.697+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:19.697+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-03T07:19:20.152+0000] {processor.py:925} INFO - DAG(s) 'lab1_dag', 'ml_dag' retrieved from /opt/airflow/dags/test.py
[2025-03-03T07:19:20.277+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:20.276+0000] {dag.py:3229} INFO - Sync 2 DAGs
[2025-03-03T07:19:20.345+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:20.345+0000] {dag.py:4156} INFO - Setting next_dagrun for lab1_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:19:20.351+0000] {logging_mixin.py:190} INFO - [2025-03-03T07:19:20.350+0000] {dag.py:4156} INFO - Setting next_dagrun for ml_dag to 2025-03-03 07:15:00+00:00, run_after=2025-03-03 07:20:00+00:00
[2025-03-03T07:19:20.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.889 seconds
